# include: 
  # file: ~/BlocksOS/blocks/device/blocks-custompi5.yaml

device: 
  name: BlocksOS
  hostname: BlocksPrinter
  user1: blocks
  user1pass: "*BlocksPrinterCustomPiOSRF50!"
  version: 0.0.1 
  class: pi5
  storage_type: sd 


image: 
  name: BlocksOS
  layout: mbr/simple_dual
  boot_part_size: 200%
  root_part_size: 300%
  rootfs_type: ext4
  compression: zstd

layer: 
  device: blocks-custompi5
  # device: rpi5
  image: blocks-image
  base: rpi-debian-bookworm

